# Try Lottery!!!!
### Generating a random numbers for lottery using a random number generator.

Well, I decided that to won the lottery, here in Brazil, it is necessary to have certain spiritual connection with random numbers, so there was this moment where the stars where  shinning, and...

```I decided to take the moment of my birth, as represented in Epoch, and use it as a seed for the random number generator of Numpy!```

If you don't know what epoch time is, it is the number of seconds since the New Year of 1970 and, besides being used in many computer systems, including satellite systems, it has an interesting history that I saw elsewhere but is also described on [Wikipedia](https://en.wikipedia.org/wiki/Unix_time#History)!

In [4]:
import numpy as np
import datetime

But let us first get my birth date and convert it to Epoch.  First, I needed to call my Mom:

*- Mom, not that I could ever remember this moment, but... please, remember me which hour in the day I was born!*

*- Well, son, last time you asked me that you where going to make an astrological map. Did you forget it?*

*- Yes mom, I narely remember the equations I work on every day...*

Then, following [this](https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime):

In [5]:
birth_date = datetime.datetime(1973,2,20,20,35)   # 20 02 1973 20:35
birth_epoch = int( birth_date.timestamp() )

### Playing Mega-Sena
We will play **Mega-Sena**, which usually offers the biggest prizes here in Brazil, and whose basic game is to play 6 numbers among 60 numbers! 

There are many ways in it which it can be done! But I will stick with the rule that the valid numbers are chosen just after seeding the random number generator with my epoch birthday time... 
It could be different, but today it is got to be this way. 

My first choice is **shuffling all numbers** and getting the first 6 numbers.

In [9]:
# Listing the possible numbers in Mega-Sena
possible_numbers = np.arange(1,61)
np.random.seed(birth_epoch)
np.random.shuffle(possible_numbers)
possible_numbers[0:10]

array([52, 43, 22, 33, 12, 20, 26,  7, 47, 58])

In [10]:
possible_numbers

array([52, 43, 22, 33, 12, 20, 26,  7, 47, 58, 57, 37, 17, 44, 39, 25, 42,
       48, 15, 23, 41,  6, 59, 40, 49, 24, 21, 10,  5,  3, 50, 54, 53, 51,
       11, 31, 32, 27, 35, 45,  1, 60, 38, 36, 18, 16, 28, 55, 56, 46, 13,
       29,  9, 14,  2, 19,  4, 34,  8, 30])

Another possibility is to choose 6 numbers among the list of possible number, without replacing them after you take them from the list! Note that I am restarting both the random seed and the list of possible numbers again because the function `np.random.shuffle()` changes the numpy array where the Mega-Sena numbers are stored.

In [7]:
possible_numbers = np.arange(1,61)
np.random.seed(birth_epoch)
np.random.choice(possible_numbers,6,replace=False)

array([52, 43, 22, 33, 12, 20])

Ha, ha! Note that, as they use the same algorithm, those are my numbers!